---
- name: "Installation - Install initscripts package for SysV compatibility"
  become: yes
  package:
    name: initscripts
    state: present
  when: ansible_os_family == "RedHat"

- name: "Installation - Add yum repository"
  become: yes
  yum_repository:
    name: kaia
    description: Kaia Package Repository
    baseurl: http://packages.kaia.io/rhel/7/kaia
    gpgcheck: no

- name: "Installation - Install Kaia Package "
  become: yes
  yum:
    name: '{{ kaia_daemon_name }}-{{ kaia_version }}-0.el7'
    state: latest
  register: is_kaia_package_installed
  until: is_kaia_package_installed is succeeded

- name: "Configuration - Make configuration directory"
  become: yes
  file:
    path: "/etc/{{ kaia_daemon_name }}/conf"
    state: "directory"

- name: "Initialization - Create kaia directory"
  become: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
  - "{{ kaia_conf.DATA_DIR }}"
  - "{{ kaia_conf.LOG_DIR }}"

- name: Check if {{ kaia_daemon_name }} service exists
  stat:
    path: /etc/systemd/system/{{ kaia_daemon_name }}.service
  register: kaia_service
  when: inventory_hostname in groups[kaia_node_type]

- name: Create systemd service file for {{ kaia_daemon_name }}
  become: yes
  template:
    src: "service.j2"
    dest: "/etc/systemd/system/{{ kaia_daemon_name }}.service"
    mode: '0644'
  when: 
    - inventory_hostname in groups[kaia_node_type]
    - not kaia_service.stat.exists

- name: Reload systemd daemon
  become: yes
  systemd:
    daemon_reload: yes
  when: 
    - inventory_hostname in groups[kaia_node_type]
    - not kaia_service.stat.exists

