---
- name: "Install binary using package"
  include_tasks: install_package.yml
  when:
  - kaia_install_mode == 'package'

- name: "Install binary using build"
  include_tasks: install_build.yml
  when:
  - kaia_install_mode == 'build'
