---
- name: "Installation - Install initscripts package for SysV compatibility"
  become: yes
  package:
    name: initscripts
    state: present
  when: ansible_os_family == "RedHat"

- name: "Installation - Copy kaia binary"
  become: yes
  copy:
    src: "{{ bin_dir }}/{{ kaia_binary_name }}"
    dest: "/bin/{{ kaia_binary_name }}"
    mode: preserve

- name: "Installation - Copy kaia init.d script"
  become: yes
  copy:
    src: "{{ bin_dir }}/{{ kaia_daemon_name }}"
    dest: "/etc/init.d/{{ kaia_daemon_name }}"
    mode: preserve

- name: "Configuration - Make configuration directory"
  become: yes
  file:
    path: "/etc/{{ kaia_daemon_name }}/conf"
    state: "directory"

- name: "Initialization - Create kaia directory"
  become: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
  - "{{ kaia_conf.DATA_DIR }}"
  - "{{ kaia_conf.LOG_DIR }}"

- name: Check if {{ kaia_daemon_name }} service exists
  stat:
    path: /etc/systemd/system/{{ kaia_daemon_name }}.service
  register: kaia_service
  when: inventory_hostname in groups[kaia_node_type]

- name: Create systemd service file for {{ kaia_daemon_name }}
  become: yes
  template:
    src: "service.j2"
    dest: "/etc/systemd/system/{{ kaia_daemon_name }}.service"
    mode: '0644'
  when: 
    - inventory_hostname in groups[kaia_node_type]
    - not kaia_service.stat.exists

- name: Reload systemd daemon
  become: yes
  systemd:
    daemon_reload: yes
  when: 
    - inventory_hostname in groups[kaia_node_type]
    - not kaia_service.stat.exists
