---
- hosts: localhost
  gather_facts: True
  vars:
    kaia_bridge_enabled: 1
    kaia_bridge_node_type: en
    kaia_bridge_node_num: 1
  roles:
  - { role: kaiaspray-defaults }
  - { role: local-init }
  tags:
  - localhost

- hosts: cn, !bridge
  gather_facts: True
  vars:
    kaia_node_type: cn
  roles:
  - { role: kaiaspray-defaults }
  - { role: node-init }

- hosts: pn, !bridge
  gather_facts: True
  vars:
    kaia_node_type: pn
  roles:
  - { role: kaiaspray-defaults }
  - { role: node-init }

- hosts: en, !bridge
  gather_facts: True
  vars:
    kaia_node_type: en
  roles:
  - { role: kaiaspray-defaults }
  - { role: node-init }

- hosts: scn, !bridge
  gather_facts: True
  vars:
    kaia_node_type: scn
    kaia_conf_override:
      NETWORK_ID: "{{ kaia_service_network_id }}"
  roles:
  - { role: kaiaspray-defaults }
  - { role: node-init }

- hosts: en, &bridge
  gather_facts: True
  vars:
    kaia_node_type: en
    kaia_bridge_enabled: 1
  roles:
  - { role: kaiaspray-defaults }
  - { role: node-init }

- hosts: scn, &bridge
  gather_facts: True
  vars:
    kaia_node_type: scn
    kaia_bridge_enabled: 1
    kaia_conf_override:
      NETWORK_ID: "{{ kaia_service_network_id }}"
  roles:
  - { role: kaiaspray-defaults }
  - { role: node-init }

- hosts: monitor
  gather_facts: True
  roles:
  - { role: kaiaspray-defaults }
  - { role: setup-docker }
  - { role: monitor-init }
