---
- hosts: localhost
  gather_facts: True
  roles:
  - { role: kaiaspray-defaults }
  - { role: local-init }
  - { role: local-build, when: kaia_install_mode == 'build' }
  tags:
  - localhost

- hosts: cn
  gather_facts: True
  vars:
    kaia_node_type: cn
  roles:
  - { role: kaiaspray-defaults }
  - { role: node-init }

- hosts: pn
  gather_facts: True
  vars:
    kaia_node_type: pn
  roles:
  - { role: kaiaspray-defaults }
  - { role: node-init }

- hosts: en
  gather_facts: True
  vars:
    kaia_node_type: en
    kaia_conf_override:
      RPC_ENABLE: 1
      RPC_API: kaia,admin,personal,eth,web3,net
  roles:
  - { role: kaiaspray-defaults }
  - { role: node-init }

- hosts: monitor
  gather_facts: True
  roles:
  - { role: kaiaspray-defaults }
  - { role: setup-docker }
  - { role: monitor-init }
