{
 "title": "Kaia Main Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "name", "query": { "query": "label_values(name)" } },
   { "name": "type", "query": { "query": "label_values(type)" } },
   {
    "name": "MaxFds",
    "query": {
     "query": "query_result(process_max_fds{name=\"$name\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "TPS (5min average)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(klaytn_blockchain_block_tx_counter{name=\"$name\"}[5m])"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klaytn_blockchain_block_tx_counter{name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Transactions in a Block",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_blockchain_block_tx_gauge",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Head Block Num",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_blockchain_head_blocknumber",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_blockchain_block_tx_counter",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Head Block Number",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klaytn_blockchain_head_blocknumber{name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Block Generation Per Second (5 min average)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(klaytn_blockchain_head_blocknumber{name=\"$name\"}[5m])"
    }
   ]
  },
  {
   "title": "Consensus Commit Sec",
   "type": "graph",
   "description": "Consensus Commit Sec",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "klaytn_consensus_istanbul_core_timer",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Block Insert Time",
   "type": "graph",
   "description": "Block Insert Time",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ns", "label": "sec" }
   ],
   "targets": [
    { "expr": "klaytn_chain_inserts", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Block Generation Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1/rate(klaytn_blockchain_head_blocknumber[30s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Pending Tx (5min avg)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(klaytn_tx_pool_pending_gauge{name=\"$name\"}[5m])"
    }
   ]
  },
  {
   "title": "Queue Tx (5min avg)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(klaytn_tx_pool_queue_gauge{name=\"$name\"}[5m])"
    }
   ]
  },
  {
   "title": "TxPool - pending",
   "type": "graph",
   "description": "txpool pending current size",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_tx_pool_pending_gauge", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "TxPool - queue",
   "type": "graph",
   "description": "txpool queue current size",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_tx_pool_queue_gauge", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Live Peer Con",
   "type": "graph",
   "description": "Live Peer Connection",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_p2p_PeerCountGauge", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "CPU (rate, sec)",
   "type": "graph",
   "description": "cpu process consume sec (rate)",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Mem(res) - all",
   "type": "graph",
   "description": "Memory Allocation (resident)",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Mem(vir) - all",
   "type": "graph",
   "description": "Memory Allocation (virtual)",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "go_goroutines",
   "type": "graph",
   "description": "Memory Allocation (resident)",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Block Insert Time",
   "type": "graph",
   "description": "Block Insert Time",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ns", "label": "sec" }
   ],
   "targets": [
    { "expr": "klaytn_chain_inserts", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Block Process Time",
   "type": "graph",
   "description": "Block Process Time",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "ns", "label": "sec" }
   ],
   "targets": [
    { "expr": "klaytn_chain_process", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Block Validation Time",
   "type": "graph",
   "description": "Block Validation Time",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ns", "label": "sec" }
   ],
   "targets": [
    { "expr": "klaytn_chain_validate", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Block Finalize Time",
   "type": "graph",
   "description": "Block Finalize Time",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "ns", "label": "sec" }
   ],
   "targets": [
    { "expr": "klaytn_chain_finalize", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Block Insert Time - Max",
   "type": "graph",
   "description": "Block Insert Time",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ns", "label": "sec" }
   ],
   "targets": [
    { "expr": "klaytn_chain_inserts_maxgauge", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Block Process Time - Max",
   "type": "graph",
   "description": "Block Process Time",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "ns", "label": "sec" }
   ],
   "targets": [
    { "expr": "klaytn_chain_process_maxgauge", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Block Validation Time - Max",
   "type": "graph",
   "description": "Block Validation Time",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ns", "label": "sec" }
   ],
   "targets": [
    { "expr": "klaytn_chain_validate_maxgauge", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Block Finalize Time - Max",
   "type": "graph",
   "description": "Block Finalize Time",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "ns", "label": "sec" }
   ],
   "targets": [
    { "expr": "klaytn_chain_finalize_maxgauge", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Hash Lock Status",
   "type": "graph",
   "description": "A gauge to record hashLock status. 1 is set if hash-locked, otherwise it's 0.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_consensus_istanbul_core_hashLock",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bad Block Counter",
   "type": "graph",
   "description": "When a bad block occurs, it increases by 1.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_blockchain_bad_block_counter",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}