{
 "title": "Klaytn Network Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CN Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CNPeerCountGauge(CN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_p2p_CNPeerCountGauge{type=\"cn\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "PNPeerCountGauge(CN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_p2p_PNPeerCountGauge{type=\"cn\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DialTryRate(CN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_p2p_DialTryCounter{type=\"cn\"}[30s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DialFailRate(CN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_p2p_DialFailCounter{type=\"cn\"}[30s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "PN Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CNPeerCountGauge(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_p2p_CNPeerCountGauge{type=\"pn\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "PNPeerCountGauge(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_p2p_PNPeerCountGauge{type=\"pn\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ENPeerCountGauge(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_p2p_ENPeerCountGauge{type=\"pn\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DialTryRate(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_p2p_DialTryCounter{type=\"pn\"}[30s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DialFailRate(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_p2p_DialFailCounter{type=\"pn\"}[30s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "EN Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PNPeerCountGauge(EN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_p2p_PNPeerCountGauge{type=\"en\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ENPeerCountGauge(EN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_p2p_PNPeerCountGauge{type=\"en\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DialTryRate(EN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_p2p_DialTryCounter{type=\"en\"}[30s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DialFailRate(EN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_p2p_DialFailCounter{type=\"en\"}[30s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Packet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "blocks_in_packets(CN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_blocks_in_packets{type=\"cn\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "blocks_in_packets(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_blocks_in_packets{type=\"pn\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "blocks_in_packets(EN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_blocks_in_packets{type=\"en\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "txs_in_packets(CN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_in_packets{type=\"cn\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "blocks_in_packets(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_in_packets{type=\"pn\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "blocks_in_packets(EN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_in_packets{type=\"en\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "blocks_out_packets(CN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_blocks_out_packets{type=\"cn\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "blocks_out_packets(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_blocks_out_packets{type=\"pn\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "blocks_out_packets(EN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_blocks_out_packets{type=\"en\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "txs_out_packets(CN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_out_packets{type=\"cn\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "txs_out_packets(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_out_packets{type=\"pn\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "txs_out_packets(EN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_out_packets{type=\"en\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}