{
 "title": "LevelDB Overview",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "State Trie DB Size by Level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "State Trie Partition 0 DB Size by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0level0_size",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0level1_size",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0level2_size",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0level3_size",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0level4_size",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "State Trie Partition 1 DB Size by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_1level0_size",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_1level1_size",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_1level2_size",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_1level3_size",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_1level4_size",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "State Trie Partition 2 DB Size by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_2level0_size",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_2level1_size",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_2level2_size",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_2level3_size",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_2level4_size",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "State Trie Partition 3 DB Size by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_3level0_size",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_3level1_size",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_3level2_size",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_3level3_size",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_3level4_size",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "State Trie DB Read by Level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "State Trie Partition 0 DB Read by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0level0_read",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0level1_read",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0level2_read",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0level3_read",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0level4_read",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "State Trie Partition 1 DB Read by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_1level0_read",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_1level1_read",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_1level2_read",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_1level3_read",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_1level4_read",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "State Trie Partition 2 DB Read by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_2level0_read",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_2level1_read",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_2level2_read",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_2level3_read",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_2level4_read",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "State Trie Partition 3 DB Read by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_3level0_read",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_3level1_read",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_3level2_read",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_3level3_read",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_3level4_read",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "State Trie DB Write by Level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "State Trie Partition 0 DB Write by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0level0_write",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0level1_write",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0level2_write",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0level3_write",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0level4_write",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "State Trie Partition 1 DB Write by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_1level0_write",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_1level1_write",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_1level2_write",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_1level3_write",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_1level4_write",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "State Trie Partition 2 DB Write by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_2level0_write",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_2level1_write",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_2level2_write",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_2level3_write",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_2level4_write",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "State Trie Partition 3 DB Write by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_3level0_write",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_3level1_write",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_3level2_write",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_3level3_write",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_3level4_write",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "State Trie DB Compaction Time by Level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "State Trie Partition 0 DB Compaction Time by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_0level0_duration[5m])",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_0level1_duration[5m])",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_0level2_duration[5m])",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_0level3_duration[5m])",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_0level4_duration[5m])",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "State Trie Partition 1 DB Compaction Time by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 28 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_1level0_duration[5m])",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_1level1_duration[5m])",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_1level2_duration[5m])",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_1level3_duration[5m])",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_1level4_duration[5m])",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "State Trie Partition 2 DB Compaction Time by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 28 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_2level0_duration[5m])",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_2level1_duration[5m])",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_2level2_duration[5m])",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_2level3_duration[5m])",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_2level4_duration[5m])",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "State Trie Partition 3 DB Compaction Time by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 28 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_3level0_duration[5m])",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_3level1_duration[5m])",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_3level2_duration[5m])",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_3level3_duration[5m])",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_statetrie_3level4_duration[5m])",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "Body DB Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Body DB Size by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_body_level0_size",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "klaytn_klay_db_chaindata_body_level1_size",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "klaytn_klay_db_chaindata_body_level2_size",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "klaytn_klay_db_chaindata_body_level3_size",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "klaytn_klay_db_chaindata_body_level4_size",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "Body DB Read by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_body_level0_read",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "klaytn_klay_db_chaindata_body_level1_read",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "klaytn_klay_db_chaindata_body_level2_read",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "klaytn_klay_db_chaindata_body_level3_read",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "klaytn_klay_db_chaindata_body_level4_read",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "Body DB Write by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_body_level0_write",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "klaytn_klay_db_chaindata_body_level1_write",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "klaytn_klay_db_chaindata_body_level2_write",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "klaytn_klay_db_chaindata_body_level3_write",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "klaytn_klay_db_chaindata_body_level4_write",
     "legendFormat": "{{name}} - L4"
    }
   ]
  },
  {
   "title": "Body DB Compaction Time by Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 37 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_klay_db_chaindata_body_level0_duration[5m])",
     "legendFormat": "{{name}} - L0"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_body_level1_duration[5m])",
     "legendFormat": "{{name}} - L1"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_body_level2_duration[5m])",
     "legendFormat": "{{name}} - L2"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_body_level3_duration[5m])",
     "legendFormat": "{{name}} - L3"
    },
    {
     "expr": "rate(klaytn_klay_db_chaindata_body_level4_duration[5m])",
     "legendFormat": "{{name}} - L4"
    }
   ]
  }
 ]
}