{
 "title": "Service Chain Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Head Block Num",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_blockchain_head_blocknumber",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VT Request Nonce",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_bridge_vt_nonce_request",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Handle Event Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_bridge_vt_event_handle",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Receipt In Packet Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_bridge_req_receipts_in_packets",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Anchroed Block Number",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_bridge_anchroing_blocknumber",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VT Handle Nonce",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_bridge_vt_nonce_handle",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Requets Event Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_bridge_vt_event_request",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Receipt Out Packet Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_bridge_req_receipts_out_packets",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VT Recovery Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_bridge_vt_event_recovery_request",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VT Request/Handle Diff",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_bridge_vt_nonce_request - klaytn_klay_bridge_vt_nonce_handle",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VT Pending Requests Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_bridge_vt_event_pend_request",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tx In Packet Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_bridge_prop_txns_in_packets",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tx Out Packet Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_bridge_prop_txns_out_packets",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}