---
- name: "Installation - Add yum repository"
  become: yes
  yum_repository:
    name: kaia
    description: Kaia Package Repository
    baseurl: http://packages.kaia.io/rhel/7/kaia
    gpgcheck: no

- name: "Installation - Install Kaia Package "
  become: yes
  yum:
    name: '{{ kaia_daemon_name }}-{{ kaia_version }}-0.el7'
    state: latest
  register: is_kaia_package_installed
  until: is_kaia_package_installed is succeeded

- name: "Installation - Install Homi Package "
  become: yes
  yum:
    name: 'homi'
    state: latest
  when: is_service_chain

- name: "Configuration - Make configuration directory"
  become: yes
  file:
    path: "/etc/{{ kaia_daemon_name }}/conf"
    state: "directory"

- name: "Configuration - Template kaia configuration"
  become: yes
  template:
    src: "kaia.conf.j2"
    dest: "/etc/{{ kaia_daemon_name }}/conf/{{ kaia_daemon_name }}.conf"

- name: "Initialization - Create kaia directory"
  become: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
  - "{{ kaia_conf.DATA_DIR }}"
  - "{{ kaia_conf.LOG_DIR }}"
