{
 "title": "Klaytn Network Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "CN Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CNPeerCountGauge(CN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_p2p_CNPeerCountGauge{instance=~\"CN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PNPeerCountGauge(CN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_p2p_PNPeerCountGauge{instance=~\"CN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DialTryRate(CN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_p2p_DialTryCounter{instance=~\"CN.*\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DialFailRate(CN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_p2p_DialFailCounter{instance=~\"CN.*\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "PN Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CNPeerCountGauge(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_p2p_CNPeerCountGauge{instance=~\"PN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PNPeerCountGauge(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_p2p_PNPeerCountGauge{instance=~\"PN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ENPeerCountGauge(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_p2p_ENPeerCountGauge{instance=~\"PN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DialTryRate(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_p2p_DialTryCounter{instance=~\"PN.*\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DialFailRate(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_p2p_DialFailCounter{instance=~\"PN.*\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "EN Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "PNPeerCountGauge(EN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_p2p_PNPeerCountGauge{instance=~\"EN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ENPeerCountGauge(EN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_p2p_PNPeerCountGauge{instance=~\"EN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DialTryRate(EN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_p2p_DialTryCounter{instance=~\"EN.*\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DialFailRate(EN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_p2p_DialFailCounter{instance=~\"EN.*\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Packet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "blocks_in_packets(CN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_blocks_in_packets{instance=~\"CN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "blocks_in_packets(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_blocks_in_packets{instance=~\"PN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "blocks_in_packets(EN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_blocks_in_packets{instance=~\"EN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "txs_in_packets(CN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_in_packets{instance=~\"CN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "blocks_in_packets(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_in_packets{instance=~\"PN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "blocks_in_packets(EN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_in_packets{instance=~\"EN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "blocks_out_packets(CN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_blocks_out_packets{instance=~\"CN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "blocks_out_packets(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_blocks_out_packets{instance=~\"PN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "blocks_out_packets(EN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_blocks_out_packets{instance=~\"EN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "txs_out_packets(CN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_out_packets{instance=~\"CN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "txs_out_packets(PN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_out_packets{instance=~\"PN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "txs_out_packets(EN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_prop_txns_out_packets{instance=~\"EN.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}