{
 "title": "Klaytn Data Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "query": "label_values(instance)" },
   {
    "name": "MaxFds",
    "query": "query_result(process_max_fds{instance=\"$server\"})"
   }
  ]
 },
 "panels": [
  { "title": "HW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LevelDB (Write)",
   "type": "graph",
   "description": "LevelDB (Write)",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "klaytn_system_disk_writedata", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "LevelDB (read)",
   "type": "graph",
   "description": "LevelDB (read)",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "klaytn_system_disk_readdata", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Mem(res) - all",
   "type": "graph",
   "description": "Memory Allocation (resident)",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Mem(vir) - all",
   "type": "graph",
   "description": "Memory Allocation (virtual)",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU (rate, sec)",
   "type": "graph",
   "description": "cpu process consume sec (rate)",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "State Trie Partition 0 DB Read Mean",
   "type": "graph",
   "description": "State Trie Partition 0 DB Read Mean",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0get_time",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "State Trie Partition 0 DB Read - Max",
   "type": "graph",
   "description": "State Trie Partition 0 DB Read - Max",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0get_time_maxgauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "State Trie Partition 0 DB Batch Write Mean",
   "type": "graph",
   "description": "State Trie Partition 0 DB Batch Write Mean",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0batchwrite_time",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "State Trie Partition 0 DB Batch Write - Max",
   "type": "graph",
   "description": "State Trie Partition 0 DB Batch Write - Max",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "klaytn_klay_db_chaindata_statetrie_0batchwrite_time_maxgauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Trie Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "klaytn_trie_memcache_nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_trie_memcache_nodes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "klaytn_trie_memcache_commit_nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_trie_memcache_commit_nodes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "klaytn_trie_memcache_gc_nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_trie_memcache_gc_nodes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "klaytn_trie_memcache_flush_nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_trie_memcache_flush_nodes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CleanCache Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_trie_memcache_clean_write",
     "legendFormat": "{{instance}}"
    },
    {}
   ]
  },
  {
   "title": "CleanCache Read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_trie_memcache_clean_read",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CleanCache Hit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_trie_memcache_clean_hit", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CleanCache Miss",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_trie_memcache_clean_miss",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Account Read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "klaytn_state_account_reads", "legendFormat": "{{instance}}" },
    {}
   ]
  },
  {
   "title": "Account Update",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 26 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "klaytn_state_account_updates", "legendFormat": "{{instance}}" },
    {}
   ]
  },
  {
   "title": "Account Commit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "klaytn_state_account_commits", "legendFormat": "{{instance}}" },
    {}
   ]
  },
  {
   "title": "Account Hash",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "klaytn_state_account_hashes", "legendFormat": "{{instance}}" },
    {}
   ]
  },
  {
   "title": "Storage Read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "klaytn_state_storage_reads", "legendFormat": "{{instance}}" },
    {}
   ]
  },
  {
   "title": "Storage Update",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 32 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "klaytn_state_storage_updates", "legendFormat": "{{instance}}" },
    {}
   ]
  },
  {
   "title": "Storage Commit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "klaytn_state_storage_commits", "legendFormat": "{{instance}}" },
    {}
   ]
  },
  {
   "title": "Storage Hash",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "klaytn_state_storage_hashes", "legendFormat": "{{instance}}" },
    {}
   ]
  },
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "TPS (rate)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(klaytn_blockchain_block_tx_counter{instance=\"$server\"}[500s])"
    }
   ]
  },
  {
   "title": "TPS (rate)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(klaytn_blockchain_block_tx_counter[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TxPool - pending",
   "type": "graph",
   "description": "txpool pending current size",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_tx_pool_pending_gauge", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Head Block Num",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_blockchain_head_blocknumber",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "go_goroutines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}