{
 "title": "Klaytn Miner Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Head Block Num",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_blockchain_head_blocknumber",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TxPool - pending",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_tx_pool_pending_gauge", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "TxPool - queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_tx_pool_queue_gauge", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Live Peer Con",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_p2p_PeerCountGauge", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Mining Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Txs in a canonical block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_blockchain_block_tx_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Txs in a mined block",
   "type": "graph",
   "description": "Number of transactions in a mined block.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_miner_tcount", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Checked Txs during mining",
   "type": "graph",
   "description": "Number of transactions checked during mining process. Does not indicate the transactions included in a mined block.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_miner_checkedtxs", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "UsedAllTxs during mining",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_miner_usedalltxs", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Block Mining Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    { "expr": "klaytn_miner_block_mining_time", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Block Mining Time - Tx Execution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "klaytn_miner_block_execute_time",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block Mining Time - Finalize",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "klaytn_miner_block_finalize_time",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Discarded Transactions Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Discarded txs during mining",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_miner_checkedtxs-klaytn_miner_tcount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nonce too low txs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_miner_nonce_low_txs", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "gas limit reached txs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "klaytn_miner_limitreached_gas_txs",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "time limit reached txs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_miner_timelimitreached", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "nonce too high txs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_miner_nonce_high_txs", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "strange error txs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "klaytn_miner_strangeerror_txs", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}