kaia_conf: "{{ kaia_conf_default | combine(kaia_conf_override) }}"
kaia_binary_name: "k{{ kaia_node_type }}"
kaia_daemon_name: "k{{ kaia_node_type }}d"
is_service_chain: "{{ kaia_node_type.startswith('s') }}"
